name             "vertx"
maintainer       "Gleb Galkin"
maintainer_email "artdaw@gmail.com"
license          "Apache 2.0"
description      "Installs vertx"
long_description "Installs vertx"
version          "0.0.1"

depends "ark"
depends "java"
